version: '3'
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - '9000:9000'
    container_name: app
    tty: true 
    stdin_open: true
    working_dir: /var/www
    volumes:
      - ./:/var/www

  webserver:
    image: nginx:stable
    container_name: webserver
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - web-pgsql
    volumes:
      - ./:/var/www
      - ./docker/app.conf:/etc/nginx/conf.d/default.conf
    links:
      - app
          
  web-pgsql:
        image: postgres:alpine
        restart: always
        container_name: web-pgsql
        volumes:
           - ./docker/conf/postgres/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
           - ./docker/data:/var/lib/postgresql/data
        ports:
           - ${DB_PORT}:${DB_EXPORT_PORT}
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASS}
            - POSTGRES_DB=${DB_NAME}
            - SCHEMA=public
            - ANON=web_anon
            - AUTHENTICATOR=authenticator
            
  composer:
    image: composer:2.0
    volumes:
      - ./:/var/www
    command: sh -c "composer install --working-dir=/var/www --ignore-platform-reqs"
